### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [1]:
#Declare the function
def string(c,i,k):
    return c[i:k+1]

#Call the function

string("Noureddine",2,6)

#print the result in a well formated format
#...

'uredd'

### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [6]:
#Declare the function
#...
def somme(a,b):
    print(type(a+b))
    return a+b
#Call with the values 1 and two
#...

somme(1,False)


<class 'int'>


1

In [7]:
somme(1,2)

<class 'int'>


3

### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [8]:
#Declare the function
#...

def string_dic(c):
    d={}
    for x in c:
        d[x]=c.count(x)
    return d    


#Print the result
#...

string_dic("ahmeddemhaait")

{'a': 3, 'h': 2, 'm': 2, 'e': 2, 'd': 2, 'i': 1, 't': 1}

### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [9]:
def print_orl2(a,b):
    n=len(a)
    for i in range(n):
        print(a[i],' ',b[n-1-i],'\n')

In [10]:
print_orl2([1,2,3],[1,2,3])

1   3 

2   2 

3   1 



### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [16]:
import numpy as np

#The input
a = np.ones((1, 10))
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
a = np.ones((1, 10)).reshape(2, -1)

#concatenate horizontally
#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])





In [19]:
def concat_array(a,b):
    ab=np.concatenate((a,b),axis=1)
    return ab


In [22]:
concat_array(a,b)

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [59]:
a = np.arange(3)
b = np.ones((3,3,3))


#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
#...
output1=[]
for x in a:
    output1=np.concatenate((output1,[x],[x],[x]))

output1=np.concatenate((output1,a,a,a))

#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])
output2=b.copy()
for x in output2:
    for y in x:
        for z in range(1,3):
            y[z]+=2**(z-1)

#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
output3 =  b.reshape(3,-1)


In [60]:
output1

array([0., 0., 0., 1., 1., 1., 2., 2., 2., 0., 1., 2., 0., 1., 2., 0., 1.,
       2.])

In [61]:
output2

array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]])

In [62]:
output3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])